apiVersion: v1
kind: Service
metadata:
  name: ip-verifier
  namespace: ip-verifier
  labels:
    app: ip-verifier
spec:
  type: LoadBalancer
  
  selector:
    app: ip-verifier
  
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
